_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.3
            "13": windows-amd64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
