_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.3
            "13": windows-amd64
num_episodes:
    value: 100
